Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -18,22 +18,25 @@ jobs:
           distribution: 'temurin'
           cache: gradle
 
-      - name: Decode Keystore
-        run: |
-          if [ -z "${{ secrets.SIGNING_KEY }}" ]; then
-            echo "Error: SIGNING_KEY is missing in Secrets!"
-            exit 1
-          fi
-          echo "${{ secrets.SIGNING_KEY }}" | base64 -d > app/mehmmet.jks
-
+      # دانلود کتابخانه مورد نیاز
       - name: Download libv2ray.aar
         run: |
           mkdir -p app/libs
           curl -L "https://github.com/2dust/AndroidLibXrayLite/releases/download/v26.7.5/libv2ray.aar" -o app/libs/libv2ray.aar
 
+      # ساخت فایل کلید مستقیماً با دستورات لینوکس
+      - name: Decode Keystore
+        env:
+          ENCODED_STRING: ${{ secrets.SIGNING_KEY }}
+        run: |
+          if [ -z "$ENCODED_STRING" ]; then
+            echo "ERROR: SIGNING_KEY is not defined in GitHub Secrets!"
+            exit 1
+          fi
+          echo "$ENCODED_STRING" | base64 -d > app/mehmmet.jks
+
       - name: Build with Gradle
         env:
-          # مسیر فایل را مستقیم می‌دهیم چون در مرحله قبل در app/mehmmet.jks ذخیره کردیم
           RELEASE_STORE_FILE: "mehmmet.jks"
           RELEASE_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
           RELEASE_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
